apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0003
  namespace:  demo
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path